### ISSUE TITLE
Priority list

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJTutorials#25]
* [ ] remove explicit import for auc etc #21 
* [ ] add tutorial for StaticTransformer/FeatureSelector #24 
* [ ] add  bootstrapping to ISL5 #22 
* [ ] add examples for composition
  * [ ] #11 
  * [ ] #7 
  * [ ] #14
